# -*- coding: utf-8 -*-
"""Quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiyewwn1KXcynz71Ab06K5R5rMhCZ73a
"""

print("T20 World Cup 2024 Quiz")
#tuple
questions = ("Who won the T20 cricket world cup 2024?","Who hit the most runs in the T20 World Cup 2024?","Which country co-hosted the T20 world cup along with United States?","How many overs are bowled in each inning of a T20 cricket match?","What does T20 stand for?")

#2-D tuple
options =(("A. USA", "B.INDIA", "C. PAKISTAN", "D. SRI LANKA"),
("A. Rohit Sharma" , "B. Quinton de Kock", "C. Rahmanullah Gurbaz", "D. Travis Head"),
("A. West Indies" , "B. India", "C. Pakistan" , "D. Bnagladesh"),
("A. 10", "B. 50", "C. 20" , "D. 25"),("A. Twenty-twenty", "B. Ten-Ten", "C. Test 20", "D. Team 20"))

answers = ("B","C","A","C","A")

guesses = []
score = 0
question_num = 0

for question in questions:
    print("                            ")
    print(question)
    for option in options[question_num]:
        print(option)

    guess = input("Enter (A, B, C, D): ").upper()
    guesses.append(guess)

    if guess == answers[question_num]:
        score += 1
        print("CORRECT!")
    else:
        print("INCORRECT!")
        print(f"{answers[question_num]} is the correct answer")
    question_num += 1

score = (score / len(questions) * 100)
print(f"Your score is: {score}%")